spring:
  config:
    activate:
      on-profile: "dev"

build:
  version: "1.0"

citoyens-service:
  message: "Welcome to Sigmas Actes related dev APIs "
  contactDetails:
    name: "SYLLA Diaguily - Product Owner"
    email: "diaguilybouna@gmail.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
  activeBranches: 
    - "version 1.0"
    - "Modifyby Diaguily"